[build]
publish = "public"
command = "hugo"

environment = { HUGO_VERSION = "0.74.3", HUGO_ENV = "production" }

[context.deploy-preview]
environment = { HUGO_ENV = "staging" }
command = "hugo -b $DEPLOY_PRIME_URL/"
